name: Fetch XAUUSD Data

on:
  schedule:
    # Runs daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas tradingview-datafeed
      
      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch XAUUSD data
        run: python scripts/fetch_data.py
      
      - name: Check data
        run: python scripts/check_data.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/XAUUSD_data.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update XAUUSD data - $(date +'%Y-%m-%d %H:%M:%S UTC')" && git push)
